# Generated by Django 4.1.7 on 2023-04-03 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
