# Generated by Django 4.1.7 on 2023-04-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0003_review_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='imagen_portada',
        ),
    ]
