# Generated by Django 4.1.7 on 2023-04-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0004_remove_review_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
