# Generated by Django 4.2 on 2023-04-03 13:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0005_review_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='imagen_portada',
            field=models.ImageField(blank=True, default='defaultimage.jpg', null=True, upload_to=''),
        ),
    ]
