# Generated by Django 4.1.7 on 2023-04-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reseñas', '0008_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
