# Generated by Django 4.1.7 on 2023-04-04 16:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reseñas', '0009_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='autor',
            field=models.ForeignKey(auto_created=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
